### ISSUE TITLE
Could you please provide the clustering scores without training on external data

### ISSUE THREAD

**Issue by RookieZB** [zhang-yu-wei/MTP-CLNN#2]
Hi, thank you for the inspiring works. I'm curious about the performance of MTP-CLNN trained on internal labeled data only, however such results are only shown by Figure 4 in the paper without specific numbers. Thus could you please provide the clustering scores of Figure 4, thank you!

**Comment by zhang-yu-wei** [comment]
Thanks for your interest to our work! I put the numbers in table here. I hope it helps you.

**BANKING**
|          |       |   0%  |       |       |  25%  |       |       |  50%  |       |       |  75%  |       |
|:--------:|:-----:|:-----:|:-----:|:-----:|:-----:|-------|:-----:|:-----:|-------|:-----:|:-----:|-------|
|          |  NMI  |  ARI  |  ACC  |  NMI  | ARI   | ACC   |  NMI  | ARI   | ACC   |  NMI  | ARI   | ACC   |
| SUP-CLNN | 40.74 |  7.50 | 18.39 | 80.91 | 55.15 | 66.05 | 84.19 | 62.13 | 73.01 | 86.56 | 68.15 | 78.10 |
| MTP-CLNN | 81.80 | 55.75 | 65.90 | 84.11 | 61.29 | 71.43 | 85.62 | 64.93 | 75.23 | 87.52 | 70.00 | 79.74 |

**StackOverflow**
|          |       |   0%  |       |       |  25%  |       |       |  50%  |       |       |  75%  |       |
|:--------:|:-----:|:-----:|:-----:|:-----:|:-----:|-------|:-----:|:-----:|-------|:-----:|:-----:|-------|
|          |  NMI  |  ARI  |  ACC  |  NMI  | ARI   | ACC   |  NMI  | ARI   | ACC   |  NMI  | ARI   | ACC   |
| SUP-CLNN | 10.35 |  1.27 | 13.70 | 75.65 | 58.23 | 77.22 | 79.77 | 69.70 | 83.91 | 81.61 | 74.23 | 86.94 |
| MTP-CLNN | 78.71 | 67.63 | 81.43 | 79.68 | 70.17 | 83.77 | 81.03 | 73.02 | 85.64 | 82.56 | 75.66 | 87.63 |

**MCID**
|          |       |   0%  |       |       |  25%  |       |       |  50%  |       |       |  75%  |       |
|:--------:|:-----:|:-----:|:-----:|:-----:|:-----:|-------|:-----:|:-----:|-------|:-----:|:-----:|-------|
|          |  NMI  |  ARI  |  ACC  |  NMI  | ARI   | ACC   |  NMI  | ARI   | ACC   |  NMI  | ARI   | ACC   |
| SUP-CLNN | 49.08 | 25.16 | 42.87 | 47.56 | 23.42 | 41.23 | 47.97 | 23.91 | 42.81 | 75.55 | 60.56 | 73.24 |
| MTP-CLNN | 79.95 | 66.71 | 79.14 | 80.24 | 66.77 | 79.20 | 79.48 | 65.71 | 77.85 | 83.75 | 73.22 | 84.36 |
