### ISSUE TITLE
Can you release more training details?

### ISSUE THREAD

**Issue by Gy915** [zhang-yu-wei/MTP-CLNN#4]
Hi, we are so interested about your excellent work. We try to reproduce your work and find your algorithm working in SNIPS dataset as well :).  However, the results in Banking dataset is far more away(nearly 10 points) than the results in the paper. 
Our main question is: 1. Do you freeze all the bert layers but the last one as the DeepAlign does? 2. Can you release the detail hyperparameters(eg. lr, epoches, batch-size) in the pretraining external datasets and internal datasets stage. 3. How do you combine the DeepAlign and MTP together? Is there any difference between your code and DeepAlign code in the [TextORI](https://github.com/thuiar/TEXTOIR).
The best way to answer my question is releasing your code :). If there is still a long time to releasing your code, the reply to the above questions will be appreciated.

**Comment by Gy915** [comment]
Is anyone here?

**Comment by zhang-yu-wei** [comment]
Code is available now. Please see the README.
